"""Create conversations table

Revision ID: da6f39b2e5a1
Revises: 8ba757083c76
Create Date: 2026-07-01 20:19:24.199705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da6f39b2e5a1'
down_revision = '8ba757083c76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_a', sa.Integer(), nullable=False),
    sa.Column('participant_b', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['participant_a'], ['users.id'], ),
    sa.ForeignKeyConstraint(['participant_b'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conversations')
    # ### end Alembic commands ###
